import type {
  AuditEvent,
  Emergency,
  Handoff,
  Machine,
  Maintenance,
  Reservation,
  Town,
} from "../types";
export const towns: Town[] = [
  {
    id: "mangalparthy",
    name: "Town A",
    shortName: "A",
    color: "#176f57",
    yard: "Town A Central Equipment Yard",
  },
  {
    id: "jalalpur",
    name: "Town B",
    shortName: "B",
    color: "#a96519",
    yard: "Town B Works Yard",
  },
  {
    id: "manepalle",
    name: "Town C",
    shortName: "C",
    color: "#315fa8",
    yard: "Town C Road Works Yard",
  },
  {
    id: "kuknoor",
    name: "Town D",
    shortName: "D",
    color: "#854f87",
    yard: "Town D Village Yard",
  },
];
export const machines: Machine[] = [
  {
    id: "MDK-GR-01",
    name: "Motor Grader",
    type: "Grader",
    jointOwner: "Town A–D Shared Equipment Pool",
    baseYard: towns[0].yard,
    currentCustodianId: "mangalparthy",
    physicalLocation: "Town A Central Equipment Yard",
    status: "IN_USE",
    fuelPercentage: 68,
    hourMeter: 1842.6,
    lastConditionSummary: "Minor wear on left rear tyre; safe to operate.",
    version: 4,
    purpose: [
      "Level unpaved roads",
      "Restore road shoulders",
      "Grade damaged approach roads",
    ],
  },
  {
    id: "MDK-BL-02",
    name: "Backhoe Loader",
    type: "Loader",
    jointOwner: "Town A–D Shared Equipment Pool",
    baseYard: towns[0].yard,
    currentCustodianId: "mangalparthy",
    physicalLocation: "Town A Yard",
    status: "AVAILABLE",
    fuelPercentage: 22,
    hourMeter: 932.1,
    lastConditionSummary: "All checks good. Fuel low.",
    version: 6,
    purpose: [
      "Clear blocked culverts",
      "Remove storm debris",
      "Excavate damaged drains",
    ],
  },
  {
    id: "MDK-PP-03",
    name: "Truck-Mounted Pothole Patcher",
    type: "Patcher",
    jointOwner: "Town A–D Shared Equipment Pool",
    baseYard: towns[0].yard,
    currentCustodianId: "jalalpur",
    physicalLocation: "Town B Works Yard",
    status: "MAINTENANCE_LOCKED",
    fuelPercentage: 47,
    hourMeter: 1268.4,
    lastConditionSummary: "Hydraulic emulsion pump leak. Do not operate.",
    version: 3,
    purpose: [
      "Repair potholes",
      "Apply bitumen and aggregate",
      "Rapid road-surface repairs",
    ],
  },
];
export const reservations: Reservation[] = [
  {
    id: "hist-a-gr-1",
    machineId: "MDK-GR-01",
    townId: "mangalparthy",
    startAt: "2026-08-28T07:30:00+05:30",
    endAt: "2026-08-28T15:45:00+05:30",
    workLocation: "North farm road",
    purpose: "Level gravel road",
    status: "COMPLETED",
    version: 1,
  },
  {
    id: "hist-b-pp-1",
    machineId: "MDK-PP-03",
    townId: "jalalpur",
    startAt: "2026-08-30T09:00:00+05:30",
    endAt: "2026-08-30T13:30:00+05:30",
    workLocation: "School road",
    purpose: "Patch potholes",
    status: "COMPLETED",
    version: 1,
  },
  {
    id: "hist-c-bl-1",
    machineId: "MDK-BL-02",
    townId: "manepalle",
    startAt: "2026-09-01T06:45:00+05:30",
    endAt: "2026-09-01T14:15:00+05:30",
    workLocation: "East culvert",
    purpose: "Clear drain silt",
    status: "COMPLETED",
    version: 1,
  },
  {
    id: "hist-d-gr-1",
    machineId: "MDK-GR-01",
    townId: "kuknoor",
    startAt: "2026-09-02T08:15:00+05:30",
    endAt: "2026-09-02T16:30:00+05:30",
    workLocation: "Market approach",
    purpose: "Restore shoulder",
    status: "COMPLETED",
    version: 1,
  },
  {
    id: "res-gr-current",
    machineId: "MDK-GR-01",
    townId: "mangalparthy",
    startAt: "2026-09-05T08:00:00+05:30",
    endAt: "2026-09-05T16:00:00+05:30",
    workLocation: "Narsapur approach road",
    purpose: "Restore damaged shoulder",
    status: "ACTIVE",
    version: 2,
  },
  {
    id: "res-gr-next",
    machineId: "MDK-GR-01",
    townId: "kuknoor",
    startAt: "2026-09-06T08:00:00+05:30",
    endAt: "2026-09-06T16:00:00+05:30",
    workLocation: "Town D west road",
    purpose: "Grade monsoon damage",
    status: "UPCOMING",
    version: 1,
  },
  {
    id: "res-bl-current",
    machineId: "MDK-BL-02",
    townId: "manepalle",
    startAt: "2026-09-05T07:00:00+05:30",
    endAt: "2026-09-05T15:00:00+05:30",
    workLocation: "Ward 3 culvert",
    purpose: "Remove silt blockage",
    status: "COMPLETED",
    version: 1,
  },
  {
    id: "res-bl-next",
    machineId: "MDK-BL-02",
    townId: "jalalpur",
    startAt: "2026-09-07T08:00:00+05:30",
    endAt: "2026-09-07T14:00:00+05:30",
    workLocation: "Tank bund drain",
    purpose: "Excavate damaged drain",
    status: "CANCELLED",
    version: 1,
  },
  {
    id: "res-pp-risk",
    machineId: "MDK-PP-03",
    townId: "kuknoor",
    startAt: "2026-09-08T08:00:00+05:30",
    endAt: "2026-09-08T16:00:00+05:30",
    workLocation: "Market road",
    purpose: "Patch potholes",
    status: "AT_RISK",
    version: 2,
  },
  {
    id: "res-preempted",
    machineId: "MDK-GR-01",
    townId: "jalalpur",
    startAt: "2026-09-04T08:00:00+05:30",
    endAt: "2026-09-04T14:00:00+05:30",
    workLocation: "School approach",
    purpose: "Road grading",
    status: "PREEMPTED",
    version: 2,
    preemptedById: "em-old",
    originalDetails: { townId: "jalalpur", purpose: "Road grading" },
  },
];
export const handoffs: Handoff[] = [
  {
    id: "handoff-pending",
    machineId: "MDK-GR-01",
    sendingTownId: "mangalparthy",
    receivingTownId: "kuknoor",
    status: "COMPLETED",
    completedAt: "2026-09-05T16:05:00+05:30",
    dueAt: "2026-09-06T07:30:00+05:30",
    version: 1,
  },
  {
    id: "handoff-complete",
    machineId: "MDK-BL-02",
    sendingTownId: "jalalpur",
    receivingTownId: "manepalle",
    status: "COMPLETED",
    dueAt: "2026-09-05T06:45:00+05:30",
    completedAt: "2026-09-05T06:51:00+05:30",
    version: 2,
  },
];
export const emergencies: Emergency[] = [
  {
    id: "em-pending",
    machineId: "MDK-BL-02",
    requestingTownId: "kuknoor",
    category: "Blocked culvert",
    startAt: "2026-09-05T17:00:00+05:30",
    endAt: "2026-09-06T11:00:00+05:30",
    affectedLocation: "Town D connector road, km 3",
    justification:
      "Heavy rain blocked the culvert and water is crossing the ambulance route.",
    status: "PENDING",
    conflictingReservationId: "res-bl-current",
  },
];
export const maintenance: Maintenance[] = [
  {
    id: "maint-hydraulic",
    machineId: "MDK-PP-03",
    category: "Hydraulic leak",
    severity: "CRITICAL",
    notes: "Emulsion pump hydraulic line leaking under pressure.",
    canMoveSafely: true,
    status: "REPAIRED_AWAITING_CLEARANCE",
    diagnosis: "Return hose seal failed.",
    repairActions: "Replaced seal and pressure-tested pump.",
    partsUsed: "Hydraulic seal kit HSK-14",
    completionNotes: "No leakage after 30-minute pressure test.",
  },
];
export const audits: Omit<
  AuditEvent,
  "previousEventHash" | "currentEventHash"
>[] = [
  {
    id: "audit-1",
    timestamp: "2026-09-01T08:03:00+05:30",
    actingRole: "CREW_CHIEF",
    actingTownId: "manepalle",
    machineId: "MDK-BL-02",
    action: "CUSTODY_TRANSFERRED",
    relatedRecordId: "handoff-complete",
    before: { custodian: "jalalpur", fuel: 78, hours: 925.4 },
    after: { custodian: "manepalle", fuel: 72, hours: 926.1 },
    reason: "No new defects observed.",
  },
  {
    id: "audit-2",
    timestamp: "2026-09-03T09:18:00+05:30",
    actingRole: "FLEET_MECHANIC",
    machineId: "MDK-PP-03",
    action: "MAINTENANCE_LOCK_APPLIED",
    relatedRecordId: "maint-hydraulic",
    before: { status: "IN_USE" },
    after: { status: "MAINTENANCE_LOCKED" },
    reason: "Hydraulic leak under pressure.",
  },
  {
    id: "audit-3",
    timestamp: "2026-09-04T06:30:00+05:30",
    actingRole: "TOWN_ADMIN",
    machineId: "MDK-GR-01",
    action: "BOOKING_PREEMPTED",
    relatedRecordId: "res-preempted",
    before: { status: "UPCOMING" },
    after: { status: "PREEMPTED" },
    reason: "Emergency ambulance access after heavy rain.",
  },
  {
    id: "audit-4",
    timestamp: "2026-09-05T10:10:00+05:30",
    actingRole: "FLEET_MECHANIC",
    machineId: "MDK-PP-03",
    action: "REPAIR_COMPLETED",
    relatedRecordId: "maint-hydraulic",
    before: { status: "REPAIR_IN_PROGRESS" },
    after: { status: "REPAIRED_AWAITING_CLEARANCE" },
    reason: "Pressure test passed; awaiting Town Admin clearance.",
  },
  {
    id: "audit-5",
    timestamp: "2026-09-05T11:25:00+05:30",
    actingRole: "CREW_CHIEF",
    actingTownId: "kuknoor",
    machineId: "MDK-BL-02",
    action: "EMERGENCY_REQUESTED",
    relatedRecordId: "em-pending",
    before: null,
    after: { status: "PENDING" },
    reason: "Blocked culvert on ambulance route.",
  },
];
